QO-14201 Create the rank system
CyrilPerrinjaquet/turnament pull request #7
Opened 2023-01-20 12:38 UTC by CyrilPerrinjaquet

added the first part

2023-01-24 08:25 UTC, dianedelallee commented on index.js
> +  if (!teamList.find((element) => element.name === teamB)) {
j'ai l'impression qu'on duplique un peu le code de la ligne 63 ici non 🤔

2023-01-24 08:26 UTC, JeromeMnd requested changes

2023-01-24 08:26 UTC, JeromeMnd commented on index.js
> +  if (!teamList.find((element) => element.name === teamA)) {
```suggestion
  if (!teamList.find((team) => team.name === teamA)) {
```

2023-01-24 08:26 UTC, JeromeMnd commented on index.js
> +  if (!teamList.find((element) => element.name === teamB)) {
```suggestion
  if (!teamList.find((team) => team.name === teamB)) {
```
C'est bien d'etre le plus précis possible quand on sait ce qu'on récupère

2023-01-24 08:26 UTC, JeromeMnd commented on index.js
> +    teamList.find((element) => element.name === team)
Pareil

2023-01-24 08:26 UTC, JeromeMnd commented on index.js
> +  const indexOfName = teamList.indexOf(
```suggestion
  const indexOfWinningTeam= teamList.indexOf(
```
Toujours le maximum d'infos sur la variable.

2023-01-24 08:26 UTC, JeromeMnd commented on index.js
> +  teamList = teamList.sort((a, b) => b.wins - a.wins);
Pareil

2023-01-24 09:10 UTC, CyrilPerrinjaquet commented on index.js
> +  if (!teamList.find((element) => element.name === teamB)) {
Okay

2023-01-24 09:12 UTC, CyrilPerrinjaquet commented on index.js
> +  if (!teamList.find((element) => element.name === teamB)) {
Hmm, je peux faire un Else if je pense ?

2023-01-24 09:12 UTC, CyrilPerrinjaquet commented on index.js
> +  const indexOfName = teamList.indexOf(
D'accord

2023-01-24 09:16 UTC, dianedelallee commented on index.js
> +  if (!teamList.find((element) => element.name === teamB)) {
nope c'est pas ca la bonne réponse ;-) 

duplication -> creation d'une fonction

2023-01-24 09:20 UTC, CyrilPerrinjaquet commented on index.js
> +  if (!teamList.find((element) => element.name === teamB)) {
J'avais une chance sur 2 hehe 😅

Je vais faire ça directement

2023-01-26 10:01 UTC, JeromeMnd approved these changes

2023-01-30 07:30 UTC, merged